### ISSUE TITLE
Bug in displaying Recent Actions

### ISSUE THREAD

**Issue by binaryblood** [douglasmiranda/django-admin-bootstrap#121]
Recent Actions contains a bug. When I add a data for a model, the recent actions is not showing the value returned from ` __str__() ` method of the model. Instead it shows like `Person object(101)`, `Employee object(121)`. But I see your screenshot displaying `Document 1`.  Why is that happening? Whats the problem actually? I'm using Django 2.0.

![ss](https://user-images.githubusercontent.com/31054280/36084174-c7059bae-0fe0-11e8-9888-ee451039e886.jpg)

**Comment by douglasmiranda** [comment]
I will check this out! 👍

**Comment by douglasmiranda** [comment]
I've tried couldn't reproduce here. If you have this problem again, provide the code so we can reproduce. =]

**Comment by merwok** [comment]
I have seen this when I add objects in the admin before adding a `__str__` method to the model class; new log entries after I add the method show the nice string version.

I suppose the admin log saves a string version of the object (rather than fetching the object and calling `str` at display time).

**Comment by douglasmiranda** [comment]
yep @merwok! That's exactly what happens! xD

- https://github.com/django/django/blob/2.1.7/django/contrib/admin/models.py#L58
- https://github.com/django/django/blob/2.1.7/django/contrib/admin/options.py#L808
