### ISSUE TITLE
Bug on Sidebar when "Customizing the AdminSite class"

### ISSUE THREAD

**Issue by douglasmiranda** [douglasmiranda/django-admin-bootstrap#54]
When customizing the AdminSite class, the apps and models registered in this new admin appear in the app list but not in sidebar menu.

``` python
from django.contrib.admin import AdminSite

from .models import MyModel

class MyAdminSite(AdminSite):
    site_header = 'Monty Python administration'

admin_site = MyAdminSite(name='myadmin')
admin_site.register(MyModel)  
```

https://docs.djangoproject.com/en/dev/ref/contrib/admin/#customizing-the-adminsite-class

This happens because I'm using:

``` python
from django.contrib.admin import site
# ...
def render_menu_app_list(context):
    # ...
    for model, model_admin in site._registry.items():
#...
```

https://github.com/douglasmiranda/django-admin-bootstrap/blob/master/bootstrap_admin/templatetags/bootstrap_admin_template_tags.py

And `site` only have those apps registered in `admin_site.name='admin'` but not those registered in `'myadmin'`.

( Need more coffee and think about this, but if someone have an idea let me know. =] )

**Comment by michaelkuty** [comment]
see https://github.com/django-admin-bootstrap/django-admin-bootstrap-demo/blob/master/example_app/site.py#L13
maybe it's not a bug

**Comment by douglasmiranda** [comment]
Thanks @michaelkuty  I will look into it this week =]

**Comment by elton2048** [comment]
I don't know if anyone cares about this issue and still I would like to post a solution which is not perfect because it needs to modify the module code.

The issue is due to the file bootstrap_admin_template_tags.py in templatetages folder only import the default site from django.contrib.admin, if there is any custom AdminSite is created it cannot use the new class as reference. As a result any new model register to the new custom AdminSite cannot be referenced on the sidebar.

To tackle the issue the custom AdminSite needs to be import to the bootstrap_admin_template_tags.py manually. 
For example, if the custom AdminSite is created in admin.py in your app.
```Python
class MyAdminSite(AdminSite):
    site_header = 'New Header'
    site_title = 'New Title'
    index_title = 'Admin Panel'

admin_site = MyAdminSite(name='myadmin')
admin_site.register(YourModel)
```

Then in bootstrap_admin_template_tags.py add the following two lines after the other modules import
```Python
from media.admin import admin_site
site = admin_site
```

In this way the site in the bootsrtap_admin_template_tags.py file is overrided by the custom AdminSite.
